### ISSUE TITLE
Evaluate Quality of Inter-Copter detection

### ISSUE THREAD

**Issue by steup** [maxct/paparazzi#8]

**Comment by tishur** [comment]
I don't know, whether we need separate experiments for this issue. But I consider this experiments as possible:
- Check difference in detection of wall or copter by other copter, when both copters are killed.
- Check difference in detection of wall or copter by other copter, when one copter is killed and second copter is in wall_avoidance mode, but firmly fixed by hand.

**Comment by maxct** [comment]
done
